import mongoose from "mongoose";
import Seminar from "../models/seminarModel.js"; // adjust path as needed

const c_by = new mongoose.Types.ObjectId("69feac1bc9dc4dd0ca5d5f10"); // common user id

const seminars = [
   {
    c_by,
    eventName: "Next-Gen AI & LLMs: From Theory to Production",
    organizer: "IIT Madras AI Lab",
    mode: "Hybrid",
    eventDate: new Date("2025-08-22"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-07-15"),
    registrationEndDate: new Date("2025-08-18"),
    totalSeats: 400,
    coverImage: "https://placehold.co/1200x600/1a1a2e/ffffff?text=AI+%26+LLMs+Seminar+2025",
    schedule: [
      { name: "Registration & Welcome Tea", startTime: "09:00", endTime: "09:30" },
      { name: "Keynote: LLM Architecture Deep Dive", startTime: "09:30", endTime: "11:00" },
      { name: "Session 1: Fine-Tuning & RLHF", startTime: "11:15", endTime: "12:30" },
      { name: "Lunch Break", startTime: "12:30", endTime: "01:30" },
      { name: "Session 2: Deploying LLMs at Scale", startTime: "01:30", endTime: "03:00" },
      { name: "Panel Q&A & Networking", startTime: "03:15", endTime: "04:30" },
    ],
    speakers: [
      { name: "Dr. Ananya Krishnan", designation: "Research Scientist, Google DeepMind", topic: "Scaling Laws and LLM Architectures" },
      { name: "Mr. Rohan Mehta", designation: "ML Engineer, OpenAI", topic: "RLHF and Alignment Techniques" },
    ],
    individualFees: 300,
    teamFees: 0,
    lateFees: 100,
    certificateAvailability: "Yes",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Google DeepMind, NVIDIA, Hugging Face",
    venueName: "IIT Madras Research Park Auditorium",
    address: "Kanagam Road, Taramani",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600113",
    geoLocation: "13.0118,80.2405",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Ramesh Kumar", phoneNumber: "9876543210", mailId: "ramesh.kumar@iitm.ac.in" },
      { type: "Student", name: "Arjun Venkatesh", phoneNumber: "9988776655", mailId: "arjun.v@iitm.ac.in" },
    ],
    eligibilityDetails: "Open to UG/PG/PhD students and working professionals with basic ML knowledge.",
    allowedDepartments: ["CSE", "IT", "ECE", "AIDS", "AIML", "MCA"],
    teamOrIndividualEvent: "Individual",
    description: "A full-day technical seminar exploring the latest advancements in large language models — from attention mechanisms to RLHF, instruction tuning, and production deployment strategies used by top AI labs.",
    tags: ["AI", "LLM", "Deep Learning", "NLP"],
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Cloud-Native DevOps: Kubernetes, CI/CD & GitOps",
    organizer: "SRMIST Cloud Computing Club",
    mode: "Online",
    eventDate: new Date("2025-09-12"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-08-10"),
    registrationEndDate: new Date("2025-09-08"),
    totalSeats: 800,
    coverImage: "https://placehold.co/1200x600/005f73/ffffff?text=DevOps+Seminar+2025",
    schedule: [
      { name: "Platform Orientation", startTime: "10:00", endTime: "10:15" },
      { name: "Session 1: Kubernetes Fundamentals", startTime: "10:15", endTime: "11:30" },
      { name: "Session 2: CI/CD Pipelines with GitHub Actions", startTime: "11:45", endTime: "01:00" },
      { name: "Break", startTime: "01:00", endTime: "01:30" },
      { name: "Session 3: GitOps with ArgoCD", startTime: "01:30", endTime: "02:45" },
      { name: "Live Demo & Q&A", startTime: "03:00", endTime: "04:00" },
    ],
    speakers: [
      { name: "Mr. Karthik Rajan", designation: "Senior DevOps Engineer, Infosys", topic: "Kubernetes in Enterprise" },
      { name: "Ms. Divya Balaji", designation: "Cloud Architect, AWS India", topic: "GitOps & ArgoCD Workflows" },
    ],
    individualFees: 150,
    teamFees: 0,
    lateFees: 50,
    certificateAvailability: "Yes",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "AWS, GitHub, CNCF",
    venueName: "Online – Zoom Webinar",
    address: "N/A",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "603203",
    geoLocation: "12.8231,80.0442",
    foodProvide: "No",
    vegNonVeg: "N/A",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Prof. Aarthi Devi", phoneNumber: "9080706050", mailId: "aarthi.d@srmist.edu.in" },
    ],
    eligibilityDetails: "Students with basic Linux and programming knowledge. Familiarity with Docker is a plus.",
    allowedDepartments: ["CSE", "IT", "ECE", "AIDS", "AIML", "MCA"],
    teamOrIndividualEvent: "Individual",
    description: "A hands-on virtual seminar covering modern DevOps practices — container orchestration with Kubernetes, automated CI/CD pipelines, and declarative GitOps deployments using ArgoCD.",
    tags: ["DevOps", "Kubernetes", "CI/CD", "Cloud"],
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Cybersecurity Essentials: Defend, Detect & Respond",
    organizer: "CEG Tech Forum",
    mode: "Offline",
    eventDate: new Date("2025-10-18"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-09-20"),
    registrationEndDate: new Date("2025-10-14"),
    totalSeats: 300,
    coverImage: "https://placehold.co/1200x600/1b1b2f/ffffff?text=Cybersecurity+Seminar+2025",
    schedule: [
      { name: "Inauguration", startTime: "09:00", endTime: "09:30" },
      { name: "Session 1: Threat Landscape 2025", startTime: "09:30", endTime: "11:00" },
      { name: "Session 2: Penetration Testing 101", startTime: "11:15", endTime: "12:30" },
      { name: "Lunch Break", startTime: "12:30", endTime: "01:30" },
      { name: "Session 3: Incident Response & SOC Workflow", startTime: "01:30", endTime: "03:00" },
      { name: "CTF Teaser & Closing", startTime: "03:15", endTime: "04:00" },
    ],
    speakers: [
      { name: "Mr. Nikhil Rajan", designation: "Security Analyst, Sequretek", topic: "Modern Threat Landscape" },
      { name: "Dr. Anand Krishnan", designation: "Professor, CEG – Anna University", topic: "Ethical Hacking Methodology" },
    ],
    individualFees: 200,
    teamFees: 0,
    lateFees: 75,
    certificateAvailability: "Yes",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Cyberdome Kerala, Sequretek, CERT-In",
    venueName: "College of Engineering Guindy – Seminar Hall",
    address: "Anna University Campus, Sardar Patel Road",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600025",
    geoLocation: "13.0107,80.2376",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Anand Krishnan", phoneNumber: "9444455566", mailId: "anand.k@ceg.ac.in" },
      { type: "Student", name: "Nikhil Rajan", phoneNumber: "9092345678", mailId: "nikhil.r@ceg.ac.in" },
    ],
    eligibilityDetails: "Open to all engineering students and IT professionals. No prior cybersecurity experience required.",
    allowedDepartments: ["CSE", "IT", "ECE", "AIDS", "MCA"],
    teamOrIndividualEvent: "Individual",
    description: "A focused one-day seminar on practical cybersecurity — covering current attack vectors, hands-on penetration testing concepts, and how Security Operations Centers detect and respond to real incidents.",
    tags: ["Cybersecurity", "Ethical Hacking", "SOC", "CERT"],
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Embedded Systems & IoT: Bridging Hardware and Cloud",
    organizer: "NIT Trichy Electronics Club",
    mode: "Offline",
    eventDate: new Date("2025-11-14"),
    registrationType: "Both",
    registrationStartDate: new Date("2025-10-10"),
    registrationEndDate: new Date("2025-11-10"),
    totalSeats: 250,
    coverImage: "https://placehold.co/1200x600/2c2c54/ffffff?text=IoT+Seminar+2025",
    schedule: [
      { name: "Welcome & Overview", startTime: "09:00", endTime: "09:30" },
      { name: "Session 1: RTOS & Microcontroller Programming", startTime: "09:30", endTime: "11:00" },
      { name: "Session 2: MQTT, Edge Computing & AWS IoT Core", startTime: "11:15", endTime: "12:45" },
      { name: "Lunch Break", startTime: "12:45", endTime: "01:45" },
      { name: "Hands-on Lab: Raspberry Pi + AWS IoT", startTime: "01:45", endTime: "03:45" },
      { name: "Q&A & Networking", startTime: "04:00", endTime: "05:00" },
    ],
    speakers: [
      { name: "Dr. Balaji Krishnamurthy", designation: "Professor, NIT Trichy", topic: "Embedded Systems Architecture" },
      { name: "Mr. Suresh Annamalai", designation: "IoT Solutions Architect, Bosch India", topic: "Industrial IoT & Edge AI" },
    ],
    individualFees: 250,
    teamFees: 400,
    lateFees: 100,
    certificateAvailability: "Yes",
    internshipOpportunity: "Yes",
    placementOpportunity: "Yes",
    industryExposure: "Yes",
    industryPartners: "Bosch, AWS India, Texas Instruments",
    venueName: "NIT Trichy Electronics Workshop Hall",
    address: "National Highway 45",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    pincode: "620015",
    geoLocation: "10.7573,78.8125",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    accommodationProvide: "Yes",
    separatedForBoysGirls: "Yes",
    onlyForOutstationParticipants: "Yes",
    incharges: [
      { type: "Faculty", name: "Dr. Balaji Krishnamurthy", phoneNumber: "9345678901", mailId: "balaji.k@nitt.edu" },
      { type: "Student", name: "Vikram Anand", phoneNumber: "9876543100", mailId: "vikram.a@nitt.edu" },
    ],
    eligibilityDetails: "ECE/EEE/Mechatronics/CSE students with basic electronics knowledge.",
    allowedDepartments: ["ECE", "EEE", "Mechatronics", "CSE", "IT"],
    teamOrIndividualEvent: "Both",
    description: "A highly practical seminar that bridges low-level embedded programming with modern cloud IoT platforms. Participants get hands-on lab experience connecting microcontrollers to AWS IoT Core via MQTT.",
    tags: ["IoT", "Embedded Systems", "RTOS", "Cloud", "Raspberry Pi"],
    isActive: true,
    posts: [],
  },

  // ─────────────────────────────────────────────
  // BUSINESS & ENTREPRENEURSHIP
  // ─────────────────────────────────────────────
  {
    c_by,
    eventName: "From Idea to IPO: The Startup Lifecycle Seminar",
    organizer: "IIM Tiruchirappalli Entrepreneurship Cell",
    mode: "Offline",
    eventDate: new Date("2025-10-25"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-09-20"),
    registrationEndDate: new Date("2025-10-20"),
    totalSeats: 200,
    coverImage: "https://placehold.co/1200x600/ff6b35/ffffff?text=Startup+Lifecycle+Seminar+2025",
    schedule: [
      { name: "Networking Breakfast", startTime: "08:30", endTime: "09:00" },
      { name: "Session 1: Ideation to MVP", startTime: "09:00", endTime: "10:30" },
      { name: "Session 2: Fundraising – Angels, VCs & Grants", startTime: "10:45", endTime: "12:15" },
      { name: "Lunch & Mentor Interaction", startTime: "12:15", endTime: "01:30" },
      { name: "Session 3: Scaling & Growth Hacking", startTime: "01:30", endTime: "03:00" },
      { name: "Fireside Chat: Founder Stories", startTime: "03:15", endTime: "04:30" },
      { name: "Networking & Closing", startTime: "04:30", endTime: "05:30" },
    ],
    speakers: [
      { name: "Mr. Aditya Srinivasan", designation: "Co-Founder, AgriTech Startup (YC W24)", topic: "Building Your MVP on a Shoestring" },
      { name: "Ms. Preethi Iyer", designation: "Partner, Sequoia Capital India", topic: "What Investors Look For" },
    ],
    individualFees: 500,
    teamFees: 0,
    lateFees: 150,
    certificateAvailability: "Yes",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Indian Angel Network, NASSCOM 10K, Tide.co",
    venueName: "IIM Trichy Seminar Hall",
    address: "Pudukkottai Road",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    pincode: "620024",
    geoLocation: "10.8139,78.6905",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Prof. Shanthi Mohan", phoneNumber: "9655432100", mailId: "shanthi.m@iimtrichy.ac.in" },
    ],
    eligibilityDetails: "Open to students, founders, and aspiring entrepreneurs from any discipline.",
    allowedDepartments: ["CSE", "IT", "Mechanical", "Civil", "MBA", "MCA", "EEE", "ECE"],
    teamOrIndividualEvent: "Individual",
    description: "A full-day immersive seminar walking participants through every stage of the startup journey — from ideating and validating a product, to securing funding and scaling to an IPO-ready company.",
    tags: ["Startup", "Entrepreneurship", "Fundraising", "VC", "Growth"],
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Digital Marketing Masterclass: SEO, Ads & Brand Building",
    organizer: "PSG College of Technology – Management Studies",
    mode: "Hybrid",
    eventDate: new Date("2025-09-27"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-08-25"),
    registrationEndDate: new Date("2025-09-23"),
    totalSeats: 350,
    coverImage: "https://placehold.co/1200x600/0f3460/ffffff?text=Digital+Marketing+Masterclass+2025",
    schedule: [
      { name: "Inauguration", startTime: "09:30", endTime: "10:00" },
      { name: "Session 1: SEO & Content Strategy", startTime: "10:00", endTime: "11:30" },
      { name: "Session 2: Google & Meta Ads Deep Dive", startTime: "11:45", endTime: "01:00" },
      { name: "Lunch Break", startTime: "01:00", endTime: "02:00" },
      { name: "Session 3: Personal Branding on LinkedIn & Instagram", startTime: "02:00", endTime: "03:30" },
      { name: "Workshop: Live Campaign Setup", startTime: "03:45", endTime: "05:00" },
    ],
    speakers: [
      { name: "Mr. Kiran Vasudev", designation: "Head of Growth, Zoho India", topic: "Inbound Marketing at Scale" },
      { name: "Ms. Nalini Chandrasekhar", designation: "Digital Strategist, Dentsu Creative", topic: "Building Brands with Performance Marketing" },
    ],
    individualFees: 350,
    teamFees: 0,
    lateFees: 100,
    certificateAvailability: "Yes",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Zoho, Google, Meta",
    venueName: "PSG Tech Seminar Complex",
    address: "Peelamedu",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641004",
    geoLocation: "11.0168,76.9558",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Prof. Meena Sundaram", phoneNumber: "9443322110", mailId: "meena.s@psgtech.ac.in" },
    ],
    eligibilityDetails: "Open to all students and professionals interested in marketing and brand strategy.",
    allowedDepartments: ["MBA", "CSE", "IT", "AIDS", "AIML", "Commerce", "Arts"],
    teamOrIndividualEvent: "Individual",
    description: "A practical masterclass on digital marketing fundamentals — from search engine optimization and paid advertising to building a strong personal brand. Includes a live hands-on campaign setup workshop.",
    tags: ["Marketing", "SEO", "Google Ads", "Branding", "Social Media"],
    isActive: true,
    posts: [],
  },

  // ─────────────────────────────────────────────
  // RESEARCH & ACADEMIA
  // ─────────────────────────────────────────────
  {
    c_by,
    eventName: "Research Methodology & Scientific Writing Workshop",
    organizer: "Anna University – Research Cell",
    mode: "Offline",
    eventDate: new Date("2025-08-30"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-07-20"),
    registrationEndDate: new Date("2025-08-26"),
    totalSeats: 150,
    coverImage: "https://placehold.co/1200x600/16213e/ffffff?text=Research+Methodology+Workshop+2025",
    schedule: [
      { name: "Welcome & Objectives", startTime: "09:00", endTime: "09:30" },
      { name: "Session 1: Formulating Research Problems & Hypotheses", startTime: "09:30", endTime: "11:00" },
      { name: "Session 2: Quantitative vs Qualitative Methods", startTime: "11:15", endTime: "12:30" },
      { name: "Lunch Break", startTime: "12:30", endTime: "01:30" },
      { name: "Session 3: Paper Writing – Structure, Language & Ethics", startTime: "01:30", endTime: "03:00" },
      { name: "Session 4: Navigating Journals, Scopus & IEEE Xplore", startTime: "03:15", endTime: "04:30" },
      { name: "Q&A & Closing", startTime: "04:30", endTime: "05:00" },
    ],
    speakers: [
      { name: "Dr. Kavitha Rajendran", designation: "Associate Professor, Anna University", topic: "Designing a Robust Research Methodology" },
      { name: "Dr. Senthil Nathan", designation: "Editor, Elsevier Journal – AI Systems", topic: "Writing Papers That Get Accepted" },
    ],
    individualFees: 400,
    teamFees: 0,
    lateFees: 100,
    certificateAvailability: "Yes",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "No",
    industryPartners: "Elsevier, IEEE, Springer",
    venueName: "Anna University Main Seminar Hall",
    address: "Sardar Patel Road, Guindy",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600025",
    geoLocation: "13.0107,80.2404",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Kavitha Rajendran", phoneNumber: "9500012345", mailId: "kavitha.r@annauniv.edu" },
      { type: "Faculty", name: "Dr. Senthil Nathan", phoneNumber: "9500098765", mailId: "senthil.n@annauniv.edu" },
    ],
    eligibilityDetails: "PG and PhD scholars from any discipline. Faculty members are also welcome.",
    allowedDepartments: ["CSE", "IT", "ECE", "EEE", "Mechanical", "Civil", "AIDS", "AIML", "Mathematics", "Physics"],
    teamOrIndividualEvent: "Individual",
    description: "A structured workshop equipping research scholars and faculty with the methodological rigour and academic writing skills needed to produce high-quality, publishable research papers in Scopus and SCI-indexed journals.",
    tags: ["Research", "Academic Writing", "Scopus", "IEEE", "PhD"],
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Quantum Computing: Principles & Near-Term Applications",
    organizer: "VIT Vellore – Centre for Quantum Science",
    mode: "Hybrid",
    eventDate: new Date("2025-11-07"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-10-01"),
    registrationEndDate: new Date("2025-11-03"),
    totalSeats: 300,
    coverImage: "https://placehold.co/1200x600/12375e/ffffff?text=Quantum+Computing+Seminar+2025",
    schedule: [
      { name: "Registration & Inauguration", startTime: "09:00", endTime: "09:45" },
      { name: "Keynote: The Quantum Era – Where Are We?", startTime: "09:45", endTime: "11:00" },
      { name: "Session 1: Qubits, Superposition & Entanglement", startTime: "11:15", endTime: "12:30" },
      { name: "Lunch", startTime: "12:30", endTime: "01:30" },
      { name: "Session 2: Quantum Algorithms – Shor's & Grover's", startTime: "01:30", endTime: "03:00" },
      { name: "Session 3: Hands-on with IBM Quantum Experience", startTime: "03:15", endTime: "04:30" },
      { name: "Panel Discussion & Networking", startTime: "04:45", endTime: "05:30" },
    ],
    speakers: [
      { name: "Dr. Priya Nair", designation: "Quantum Research Lead, VIT", topic: "Quantum Mechanics for Computer Scientists" },
      { name: "Mr. Arun Sethupathi", designation: "Quantum Solutions Engineer, IBM India", topic: "Practical Quantum with Qiskit" },
    ],
    individualFees: 350,
    teamFees: 0,
    lateFees: 100,
    certificateAvailability: "Yes",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "IBM Quantum, IonQ, D-Wave",
    venueName: "VIT Technology Tower – Conference Hall",
    address: "Katpadi Road",
    city: "Vellore",
    state: "Tamil Nadu",
    pincode: "632014",
    geoLocation: "12.9698,79.1559",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Priya Nair", phoneNumber: "9751234567", mailId: "priya.nair@vit.ac.in" },
      { type: "Student", name: "Deepak Suresh", phoneNumber: "9840011223", mailId: "deepak.s@vit.ac.in" },
    ],
    eligibilityDetails: "UG/PG/PhD students with basic linear algebra and programming knowledge. Curiosity about physics is a plus.",
    allowedDepartments: ["CSE", "IT", "ECE", "Physics", "Mathematics", "AIDS"],
    teamOrIndividualEvent: "Individual",
    description: "An exploratory seminar demystifying quantum computing — from qubits and quantum gates to real-world algorithms and hands-on experimentation using IBM's cloud quantum computers via Qiskit.",
    tags: ["Quantum Computing", "Qiskit", "IBM Quantum", "Algorithms"],
    isActive: true,
    posts: [],
  },

  // ─────────────────────────────────────────────
  // DESIGN & CREATIVE
  // ─────────────────────────────────────────────
  {
    c_by,
    eventName: "UX Research Intensive: Designing for Real Users",
    organizer: "Amrita School of Engineering – Design Dept.",
    mode: "Offline",
    eventDate: new Date("2025-09-20"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-08-15"),
    registrationEndDate: new Date("2025-09-16"),
    totalSeats: 120,
    coverImage: "https://placehold.co/1200x600/f7b731/000000?text=UX+Research+Seminar+2025",
    schedule: [
      { name: "Welcome & Ice-breaker", startTime: "09:00", endTime: "09:30" },
      { name: "Session 1: UX Research Methods Overview", startTime: "09:30", endTime: "11:00" },
      { name: "Session 2: User Interviews – Live Demo & Practice", startTime: "11:15", endTime: "12:30" },
      { name: "Lunch", startTime: "12:30", endTime: "01:30" },
      { name: "Session 3: Affinity Mapping & Insight Synthesis", startTime: "01:30", endTime: "03:00" },
      { name: "Session 4: Usability Testing on Real Products", startTime: "03:15", endTime: "04:45" },
      { name: "Portfolio Tips & Closing", startTime: "05:00", endTime: "05:30" },
    ],
    speakers: [
      { name: "Dr. Lakshmi Prabha", designation: "Professor & UX Lead, Amrita", topic: "Bridging Research and Design Decisions" },
      { name: "Ms. Sanjana Mohan", designation: "UX Designer, Razorpay", topic: "How Razorpay Does User Research at Scale" },
    ],
    individualFees: 300,
    teamFees: 0,
    lateFees: 75,
    certificateAvailability: "Yes",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Figma, Adobe, Razorpay Design Team",
    venueName: "Amrita School of Engineering – Design Studio",
    address: "Ettimadai",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641112",
    geoLocation: "10.9081,76.9320",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Lakshmi Prabha", phoneNumber: "9361298765", mailId: "lakshmi.p@amrita.edu" },
      { type: "Student", name: "Sanjana Mohan", phoneNumber: "9876012345", mailId: "sanjana.m@amrita.edu" },
    ],
    eligibilityDetails: "Design, CSE, and interdisciplinary students. Interest in human-centred design is essential.",
    allowedDepartments: ["Design", "CSE", "IT", "AIDS", "AIML", "MBA"],
    teamOrIndividualEvent: "Individual",
    description: "A hands-on seminar covering the end-to-end UX research process — from planning user interviews and usability tests to synthesizing insights into actionable design decisions using affinity mapping and jobs-to-be-done frameworks.",
    tags: ["UX", "User Research", "Design Thinking", "Figma", "Usability"],
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Sustainable Architecture & Green Building Design",
    organizer: "Thiagarajar College of Engineering – Civil Dept.",
    mode: "Offline",
    eventDate: new Date("2025-12-13"),
    registrationType: "Both",
    registrationStartDate: new Date("2025-11-10"),
    registrationEndDate: new Date("2025-12-09"),
    totalSeats: 180,
    coverImage: "https://placehold.co/1200x600/2d6a4f/ffffff?text=Green+Architecture+Seminar+2025",
    schedule: [
      { name: "Registration & Welcome", startTime: "09:00", endTime: "09:30" },
      { name: "Session 1: Principles of Sustainable Architecture", startTime: "09:30", endTime: "11:00" },
      { name: "Session 2: LEED & GRIHA Rating Systems", startTime: "11:15", endTime: "12:30" },
      { name: "Lunch Break", startTime: "12:30", endTime: "01:30" },
      { name: "Session 3: Net-Zero Buildings – Case Studies from India", startTime: "01:30", endTime: "03:00" },
      { name: "Session 4: Passive Design & Climate-Responsive Architecture", startTime: "03:15", endTime: "04:30" },
      { name: "Open Q&A & Closing Ceremony", startTime: "04:45", endTime: "05:30" },
    ],
    speakers: [
      { name: "Dr. Muthu Krishnan", designation: "Professor, TCE – Civil Engineering", topic: "Sustainable Construction Materials" },
      { name: "Ar. Vani Ramasubramanian", designation: "Principal Architect, Green Studio Chennai", topic: "Net-Zero Buildings – India's Path Forward" },
    ],
    individualFees: 250,
    teamFees: 400,
    lateFees: 100,
    certificateAvailability: "Yes",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "TNPCB, Grundfos, Envirofit India",
    venueName: "Thiagarajar College of Engineering – Civil Seminar Hall",
    address: "Thiruparankundram Road",
    city: "Madurai",
    state: "Tamil Nadu",
    pincode: "625015",
    geoLocation: "9.8936,78.0727",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Muthu Krishnan", phoneNumber: "9444401234", mailId: "muthu.k@tce.edu" },
      { type: "Faculty", name: "Dr. Shalini Gopal", phoneNumber: "9500087654", mailId: "shalini.g@tce.edu" },
    ],
    eligibilityDetails: "Civil engineering and architecture students. Professionals from the construction industry are also welcome.",
    allowedDepartments: ["Civil", "Architecture", "Mechanical", "Environmental Engineering", "CSE"],
    teamOrIndividualEvent: "Both",
    description: "A comprehensive seminar on sustainable architecture principles — passive design, green rating systems (LEED/GRIHA), net-zero construction techniques, and how India's built environment can meet its 2070 climate commitments.",
    tags: ["Architecture", "Sustainability", "LEED", "Green Building", "Net-Zero"],
    isActive: true,
    posts: [],
  },
];

/**
 * Seeds 10 seminar documents into the database.
 * Call this after establishing a MongoDB connection.
 */
export async function seedSeminars() {
  try {
    // Insert one by one to catch which document/field fails
    for (let i = 0; i < seminars.length; i++) {
      try {
        const doc = await Seminar.create({...seminars[i],eventType:"Technical"});
        console.log(`✅ Inserted: ${doc.eventName}`);
      } catch (err) {
        console.error(`❌ Failed [${i}] ${seminars[i].eventName}:`, err.message);
      }
    }
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    throw error;
  }
}
// --- Optional: Run directly with `node seedSeminars.js` ---
// Uncomment the block below if you want to run this file standalone.

/*
import "dotenv/config";

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("🔗 Connected to MongoDB");
  await seedSeminars();
  await mongoose.disconnect();
  console.log("🔌 Disconnected.");
  process.exit(0);
})();
*/