import mongoose from "mongoose";
import Conference from "../models/conferenceModel.js"; // adjust path as needed

const c_by = new mongoose.Types.ObjectId("69feac1bc9dc4dd0ca5d5f10"); // common user id

const conferences = [
  {
    c_by,
    eventName: "TechSpark National Hackathon 2025",
    organizer: "IIT Madras Tech Club",
    mode: "Offline",
    eventDate: new Date("2025-08-15"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-07-01"),
    registrationEndDate: new Date("2025-08-10"),
    totalSeats: 300,
    coverImage: "https://placehold.co/1200x600/1a1a2e/ffffff?text=TechSpark+2025",
    rounds: [
      { roundNumber: "1", roundName: "Idea Submission", roundDescription: "Submit a 2-page problem statement and proposed solution." },
      { roundNumber: "2", roundName: "Prototype Demo", roundDescription: "Present a working prototype to a panel of judges." },
      { roundNumber: "3", roundName: "Grand Finale", roundDescription: "Final pitch and live Q&A with industry experts." },
    ],
    schedule: [
      { name: "Registration & Kit Distribution", startTime: "08:00", endTime: "09:00" },
      { name: "Opening Ceremony", startTime: "09:00", endTime: "10:00" },
      { name: "Hacking Begins", startTime: "10:00", endTime: "10:00" },
      { name: "Final Judging", startTime: "10:00", endTime: "11:59" },
    ],
    individualFees: 0,
    teamFees: 500,
    lateFees: 100,
    firstPrize: "₹1,00,000 + Internship",
    secondPrize: "₹50,000",
    thirdPrize: "₹25,000",
    participationPrize: "Certificate + Goodies",
    internshipOpportunity: "Yes",
    placementOpportunity: "Yes",
    industryExposure: "Yes",
    industryPartners: "Google, Microsoft, Zoho",
    venueName: "IIT Madras Research Park",
    address: "Kanagam Road, Taramani",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600113",
    geoLocation: "13.0118,80.2405",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    midnightSnacks: "Yes",
    accommodationProvide: "Yes",
    separatedForBoysGirls: "Yes",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Ramesh Kumar", phoneNumber: "9876543210", mailId: "ramesh.kumar@iitm.ac.in" },
      { type: "Student", name: "Arjun Venkatesh", phoneNumber: "9988776655", mailId: "arjun.v@iitm.ac.in" },
    ],
    eligibilityDetails: "Open to all UG/PG students from any recognized institution.",
    allowedDepartments: ["CSE", "IT", "ECE", "EEE", "MCA"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 2,
    teamSizeMaximum: 4,
    certificateAvailability: "Yes",
    description: "TechSpark is a 24-hour national-level hackathon where teams compete to build innovative tech solutions for real-world problems across domains like healthcare, fintech, and sustainability.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "CodeQuest Inter-College Programming Contest",
    organizer: "PSG College of Technology",
    mode: "Online",
    eventDate: new Date("2025-09-05"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-08-01"),
    registrationEndDate: new Date("2025-09-01"),
    totalSeats: 500,
    coverImage: "https://placehold.co/1200x600/0f3460/ffffff?text=CodeQuest+2025",
    rounds: [
      { roundNumber: "1", roundName: "Online Qualifier", roundDescription: "MCQ-based aptitude and basic programming test on HackerRank." },
      { roundNumber: "2", roundName: "Advanced Coding", roundDescription: "3-hour competitive programming round with 5 algorithmic problems." },
    ],
    schedule: [
      { name: "Round 1 – Qualifier", startTime: "10:00", endTime: "11:00" },
      { name: "Break", startTime: "11:00", endTime: "12:00" },
      { name: "Round 2 – Advanced Coding", startTime: "12:00", endTime: "03:00" },
      { name: "Results Announcement", startTime: "05:00", endTime: "05:30" },
    ],
    individualFees: 200,
    teamFees: 0,
    lateFees: 50,
    firstPrize: "₹30,000",
    secondPrize: "₹15,000",
    thirdPrize: "₹7,500",
    participationPrize: "E-Certificate",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "No",
    industryPartners: "HackerRank, JetBrains",
    venueName: "Online – HackerRank Platform",
    address: "N/A",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641004",
    geoLocation: "11.0168,76.9558",
    foodProvide: "No",
    vegNonVeg: "N/A",
    midnightSnacks: "No",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Prof. Meena Sundaram", phoneNumber: "9443322110", mailId: "meena.s@psgtech.ac.in" },
    ],
    eligibilityDetails: "Any student currently pursuing B.E./B.Tech/M.E./M.Tech/MCA.",
    allowedDepartments: ["CSE", "IT", "MCA", "AIDS", "AIML"],
    teamOrIndividualEvent: "Individual",
    teamSizeMinimum: 1,
    teamSizeMaximum: 1,
    certificateAvailability: "Yes",
    description: "CodeQuest challenges participants with high-intensity algorithmic problems to sharpen problem-solving skills. The top performers will be featured on a national leaderboard.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "AI Frontier Conference 2025",
    organizer: "Anna University",
    mode: "Hybrid",
    eventDate: new Date("2025-10-20"),
    registrationType: "Both",
    registrationStartDate: new Date("2025-09-01"),
    registrationEndDate: new Date("2025-10-15"),
    totalSeats: 600,
    coverImage: "https://placehold.co/1200x600/16213e/ffffff?text=AI+Frontier+2025",
    rounds: [
      { roundNumber: "1", roundName: "Paper Submission", roundDescription: "Submit a research abstract of 500 words for review." },
      { roundNumber: "2", roundName: "Paper Presentation", roundDescription: "Present your research to a panel of academics and industry leaders." },
    ],
    schedule: [
      { name: "Inauguration & Keynote", startTime: "09:00", endTime: "10:30" },
      { name: "Technical Sessions – Track A & B", startTime: "10:30", endTime: "01:00" },
      { name: "Lunch Break", startTime: "01:00", endTime: "02:00" },
      { name: "Panel Discussion: Future of AI", startTime: "02:00", endTime: "03:30" },
      { name: "Valedictory & Prize Distribution", startTime: "04:00", endTime: "05:00" },
    ],
    individualFees: 400,
    teamFees: 700,
    lateFees: 150,
    firstPrize: "Best Paper Award – ₹20,000",
    secondPrize: "Runner-up Paper – ₹10,000",
    thirdPrize: "Merit Award – ₹5,000",
    participationPrize: "Participation Certificate + Conference Kit",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "NVIDIA, IBM Research, ISRO",
    venueName: "Anna University Auditorium",
    address: "Sardar Patel Road, Guindy",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600025",
    geoLocation: "13.0107,80.2404",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    midnightSnacks: "No",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Kavitha Rajendran", phoneNumber: "9500012345", mailId: "kavitha.r@annauniv.edu" },
      { type: "Faculty", name: "Dr. Senthil Nathan", phoneNumber: "9500098765", mailId: "senthil.n@annauniv.edu" },
    ],
    eligibilityDetails: "UG, PG, and PhD scholars from any discipline. Industry professionals are also welcome.",
    allowedDepartments: ["CSE", "IT", "ECE", "EEE", "Mechanical", "Civil", "AIDS", "AIML"],
    teamOrIndividualEvent: "Individual",
    teamSizeMinimum: 1,
    teamSizeMaximum: 3,
    certificateAvailability: "Yes",
    description: "AI Frontier is a premier conference bringing together researchers, academicians, and industry practitioners to discuss cutting-edge advancements in Artificial Intelligence, Machine Learning, and Deep Learning.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "RoboWars Championship 2025",
    organizer: "NIT Trichy Robotics Club",
    mode: "Offline",
    eventDate: new Date("2025-11-10"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-10-01"),
    registrationEndDate: new Date("2025-11-05"),
    totalSeats: 150,
    coverImage: "https://placehold.co/1200x600/2c2c54/ffffff?text=RoboWars+2025",
    rounds: [
      { roundNumber: "1", roundName: "Design Review", roundDescription: "Submit robot design specifications and safety compliance docs." },
      { roundNumber: "2", roundName: "Elimination Rounds", roundDescription: "Bracket-style combat between robots in a 4x4m arena." },
      { roundNumber: "3", roundName: "Grand Finals", roundDescription: "Top 4 teams battle for the championship title." },
    ],
    schedule: [
      { name: "Robot Inspection & Registration", startTime: "07:30", endTime: "09:00" },
      { name: "Elimination Rounds", startTime: "09:30", endTime: "04:00" },
      { name: "Semi-Finals", startTime: "04:30", endTime: "06:00" },
      { name: "Grand Finals & Prize Ceremony", startTime: "06:30", endTime: "08:00" },
    ],
    individualFees: 0,
    teamFees: 1500,
    lateFees: 300,
    firstPrize: "₹75,000 + Trophy",
    secondPrize: "₹35,000 + Trophy",
    thirdPrize: "₹15,000 + Medal",
    participationPrize: "Certificate + Stickers",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Bosch, Winjit Technologies",
    venueName: "NIT Trichy Central Arena",
    address: "National Highway 45",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    pincode: "620015",
    geoLocation: "10.7573,78.8125",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    midnightSnacks: "No",
    accommodationProvide: "Yes",
    separatedForBoysGirls: "Yes",
    onlyForOutstationParticipants: "Yes",
    incharges: [
      { type: "Faculty", name: "Dr. Balaji Krishnamurthy", phoneNumber: "9345678901", mailId: "balaji.k@nitt.edu" },
      { type: "Student", name: "Vikram Anand", phoneNumber: "9876543100", mailId: "vikram.a@nitt.edu" },
    ],
    eligibilityDetails: "Open to engineering students from any recognized college. Robots must comply with NIT Trichy RoboWars safety norms.",
    allowedDepartments: ["Mechanical", "ECE", "EEE", "CSE", "Mechatronics"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 3,
    teamSizeMaximum: 6,
    certificateAvailability: "Yes",
    description: "RoboWars is a full-combat robotics championship where teams design and battle autonomous/semi-autonomous machines. Experience adrenaline-packed rounds in a specially constructed safety arena.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "CloudOps Summit 2025",
    organizer: "SRMIST Cloud Computing Club",
    mode: "Online",
    eventDate: new Date("2025-09-22"),
    registrationType: "Individual",
    registrationStartDate: new Date("2025-08-15"),
    registrationEndDate: new Date("2025-09-18"),
    totalSeats: 1000,
    coverImage: "https://placehold.co/1200x600/005f73/ffffff?text=CloudOps+Summit+2025",
    rounds: [
      { roundNumber: "1", roundName: "Cloud Quiz", roundDescription: "45-minute MCQ quiz on AWS, Azure, and GCP fundamentals." },
      { roundNumber: "2", roundName: "Architecture Challenge", roundDescription: "Design a scalable cloud architecture for a given scenario within 2 hours." },
    ],
    schedule: [
      { name: "Orientation & Platform Walkthrough", startTime: "09:30", endTime: "10:00" },
      { name: "Cloud Quiz", startTime: "10:00", endTime: "10:45" },
      { name: "Architecture Challenge", startTime: "11:30", endTime: "01:30" },
      { name: "Results & Webinar by AWS Expert", startTime: "03:00", endTime: "04:30" },
    ],
    individualFees: 150,
    teamFees: 0,
    lateFees: 50,
    firstPrize: "₹20,000 + AWS Voucher",
    secondPrize: "₹10,000 + Azure Voucher",
    thirdPrize: "₹5,000",
    participationPrize: "E-Certificate",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "AWS, Microsoft Azure, Google Cloud",
    venueName: "Online – Zoom & HackerEarth",
    address: "N/A",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "603203",
    geoLocation: "12.8231,80.0442",
    foodProvide: "No",
    vegNonVeg: "N/A",
    midnightSnacks: "No",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Prof. Aarthi Devi", phoneNumber: "9080706050", mailId: "aarthi.d@srmist.edu.in" },
    ],
    eligibilityDetails: "Students pursuing any degree with basic knowledge of cloud platforms.",
    allowedDepartments: ["CSE", "IT", "ECE", "AIDS", "AIML", "MCA"],
    teamOrIndividualEvent: "Individual",
    teamSizeMinimum: 1,
    teamSizeMaximum: 1,
    certificateAvailability: "Yes",
    description: "CloudOps Summit tests participants on their cloud computing and DevOps skills through a two-round competitive format. Winners receive cloud credits and get featured in SRM's tech newsletter.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "DataViz Challenge 2025",
    organizer: "Vellore Institute of Technology",
    mode: "Hybrid",
    eventDate: new Date("2025-10-08"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-09-10"),
    registrationEndDate: new Date("2025-10-04"),
    totalSeats: 200,
    coverImage: "https://placehold.co/1200x600/6a0572/ffffff?text=DataViz+Challenge+2025",
    rounds: [
      { roundNumber: "1", roundName: "Dataset Analysis", roundDescription: "Analyze a provided dataset and submit an insights report within 3 hours." },
      { roundNumber: "2", roundName: "Dashboard Presentation", roundDescription: "Build an interactive dashboard and present insights to judges." },
    ],
    schedule: [
      { name: "Briefing & Dataset Distribution", startTime: "09:00", endTime: "09:30" },
      { name: "Round 1 – Analysis", startTime: "09:30", endTime: "12:30" },
      { name: "Lunch Break", startTime: "12:30", endTime: "01:15" },
      { name: "Round 2 – Dashboard Presentation", startTime: "01:30", endTime: "04:00" },
      { name: "Results & Networking", startTime: "04:30", endTime: "05:30" },
    ],
    individualFees: 0,
    teamFees: 600,
    lateFees: 100,
    firstPrize: "₹40,000",
    secondPrize: "₹20,000",
    thirdPrize: "₹10,000",
    participationPrize: "Certificate + Dataset Access for 1 Year",
    internshipOpportunity: "Yes",
    placementOpportunity: "Yes",
    industryExposure: "Yes",
    industryPartners: "Tableau, Mu Sigma, Fractal Analytics",
    venueName: "VIT Technology Tower",
    address: "Katpadi Road",
    city: "Vellore",
    state: "Tamil Nadu",
    pincode: "632014",
    geoLocation: "12.9698,79.1559",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    midnightSnacks: "No",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Priya Nair", phoneNumber: "9751234567", mailId: "priya.nair@vit.ac.in" },
      { type: "Student", name: "Deepak Suresh", phoneNumber: "9840011223", mailId: "deepak.s@vit.ac.in" },
    ],
    eligibilityDetails: "Open to UG/PG students from any branch. Basic knowledge of Python/R or any BI tool is preferred.",
    allowedDepartments: ["CSE", "IT", "AIDS", "AIML", "MCA", "Mathematics"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 2,
    teamSizeMaximum: 3,
    certificateAvailability: "Yes",
    description: "DataViz Challenge pushes teams to extract meaningful stories from raw datasets and communicate them through compelling visual dashboards. The event emphasizes analytical thinking and design aesthetics.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Ethical Hacking CTF – CyberStorm 2025",
    organizer: "CEG Tech Forum",
    mode: "Offline",
    eventDate: new Date("2025-12-06"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-11-01"),
    registrationEndDate: new Date("2025-12-01"),
    totalSeats: 250,
    coverImage: "https://placehold.co/1200x600/1b1b2f/ffffff?text=CyberStorm+CTF+2025",
    rounds: [
      { roundNumber: "1", roundName: "Jeopardy CTF", roundDescription: "Solve cybersecurity challenges across web, crypto, forensics, and reverse engineering." },
      { roundNumber: "2", roundName: "Attack-Defense", roundDescription: "Teams protect their own server while attacking others in a live network." },
    ],
    schedule: [
      { name: "Check-in & Environment Setup", startTime: "08:30", endTime: "09:30" },
      { name: "Jeopardy CTF Round", startTime: "09:30", endTime: "01:30" },
      { name: "Lunch & Score Reveal", startTime: "01:30", endTime: "02:30" },
      { name: "Attack-Defense Round", startTime: "02:30", endTime: "06:00" },
      { name: "Prize Distribution", startTime: "06:30", endTime: "07:30" },
    ],
    individualFees: 0,
    teamFees: 800,
    lateFees: 200,
    firstPrize: "₹60,000 + Internship at Cybersecurity Firm",
    secondPrize: "₹30,000",
    thirdPrize: "₹12,000",
    participationPrize: "Certificate + Swag Kit",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Cyberdome Kerala, Sequretek, CERT-In",
    venueName: "College of Engineering Guindy",
    address: "Anna University Campus, Sardar Patel Road",
    city: "Chennai",
    state: "Tamil Nadu",
    pincode: "600025",
    geoLocation: "13.0107,80.2376",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    midnightSnacks: "No",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Anand Krishnan", phoneNumber: "9444455566", mailId: "anand.k@ceg.ac.in" },
      { type: "Student", name: "Nikhil Rajan", phoneNumber: "9092345678", mailId: "nikhil.r@ceg.ac.in" },
    ],
    eligibilityDetails: "Students from any engineering background with interest in cybersecurity. No prior CTF experience required.",
    allowedDepartments: ["CSE", "IT", "ECE", "AIDS"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 2,
    teamSizeMaximum: 4,
    certificateAvailability: "Yes",
    description: "CyberStorm is a 2-round Capture The Flag competition covering offensive and defensive cybersecurity skills. Real-world attack-defense scenarios prepare participants for professional penetration testing and SOC roles.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "StartUp Pitch Fest 2025",
    organizer: "IIM Tiruchirappalli Entrepreneurship Cell",
    mode: "Offline",
    eventDate: new Date("2025-11-28"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-10-15"),
    registrationEndDate: new Date("2025-11-20"),
    totalSeats: 100,
    coverImage: "https://placehold.co/1200x600/ff6b35/ffffff?text=StartUp+Pitch+Fest+2025",
    rounds: [
      { roundNumber: "1", roundName: "Elevator Pitch", roundDescription: "2-minute pitch to a screening panel to qualify for the main stage." },
      { roundNumber: "2", roundName: "Investor Panel", roundDescription: "10-minute pitch followed by a 5-minute Q&A with angel investors." },
    ],
    schedule: [
      { name: "Networking Breakfast", startTime: "08:00", endTime: "09:00" },
      { name: "Elevator Pitches", startTime: "09:00", endTime: "12:00" },
      { name: "Lunch & Mentor Interaction", startTime: "12:00", endTime: "01:30" },
      { name: "Investor Panel Pitches", startTime: "01:30", endTime: "05:00" },
      { name: "Award Ceremony & Networking Dinner", startTime: "06:00", endTime: "08:00" },
    ],
    individualFees: 0,
    teamFees: 1000,
    lateFees: 250,
    firstPrize: "₹2,00,000 Seed Funding + Mentorship",
    secondPrize: "₹75,000 Seed Funding",
    thirdPrize: "₹25,000",
    participationPrize: "Certificate + Incubator Access",
    internshipOpportunity: "No",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Indian Angel Network, NASSCOM 10K, Tide.co",
    venueName: "IIM Trichy Convocation Hall",
    address: "Pudukkottai Road",
    city: "Tiruchirappalli",
    state: "Tamil Nadu",
    pincode: "620024",
    geoLocation: "10.8139,78.6905",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    midnightSnacks: "No",
    accommodationProvide: "Yes",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Prof. Shanthi Mohan", phoneNumber: "9655432100", mailId: "shanthi.m@iimtrichy.ac.in" },
    ],
    eligibilityDetails: "Open to student entrepreneurs and early-stage startup founders. The team must have a viable MVP or business plan.",
    allowedDepartments: ["CSE", "IT", "Mechanical", "Civil", "MBA", "MCA", "EEE", "ECE"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 1,
    teamSizeMaximum: 5,
    certificateAvailability: "Yes",
    description: "StartUp Pitch Fest connects emerging student entrepreneurs with seasoned angel investors and industry mentors. Selected startups can receive seed funding and 6 months of incubation support.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "Web Wizards UI/UX Designathon",
    organizer: "Amrita School of Engineering",
    mode: "Offline",
    eventDate: new Date("2025-09-15"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-08-10"),
    registrationEndDate: new Date("2025-09-10"),
    totalSeats: 180,
    coverImage: "https://placehold.co/1200x600/f7b731/000000?text=Web+Wizards+2025",
    rounds: [
      { roundNumber: "1", roundName: "Wireframe Submission", roundDescription: "Submit low-fidelity wireframes for an assigned problem statement." },
      { roundNumber: "2", roundName: "High-Fidelity Prototype", roundDescription: "Build a high-fidelity clickable prototype using Figma or Adobe XD." },
      { roundNumber: "3", roundName: "Usability Presentation", roundDescription: "Present prototype and walk judges through the user journey." },
    ],
    schedule: [
      { name: "Problem Statement Reveal", startTime: "09:00", endTime: "09:30" },
      { name: "Wireframe Round", startTime: "09:30", endTime: "12:00" },
      { name: "Lunch", startTime: "12:00", endTime: "01:00" },
      { name: "Prototype Round", startTime: "01:00", endTime: "05:00" },
      { name: "Presentations & Judging", startTime: "05:30", endTime: "07:30" },
    ],
    individualFees: 0,
    teamFees: 450,
    lateFees: 100,
    firstPrize: "₹25,000 + Figma Pro License",
    secondPrize: "₹12,000",
    thirdPrize: "₹6,000",
    participationPrize: "Certificate",
    internshipOpportunity: "Yes",
    placementOpportunity: "No",
    industryExposure: "Yes",
    industryPartners: "Figma, Adobe, Razorpay Design Team",
    venueName: "Amrita School of Engineering",
    address: "Ettimadai",
    city: "Coimbatore",
    state: "Tamil Nadu",
    pincode: "641112",
    geoLocation: "10.9081,76.9320",
    foodProvide: "Yes",
    vegNonVeg: "Veg Only",
    midnightSnacks: "No",
    accommodationProvide: "No",
    separatedForBoysGirls: "No",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Lakshmi Prabha", phoneNumber: "9361298765", mailId: "lakshmi.p@amrita.edu" },
      { type: "Student", name: "Sanjana Mohan", phoneNumber: "9876012345", mailId: "sanjana.m@amrita.edu" },
    ],
    eligibilityDetails: "Students from any engineering or design background. Familiarity with at least one design tool (Figma, XD, Sketch) is mandatory.",
    allowedDepartments: ["CSE", "IT", "AIDS", "AIML", "Design", "ECE"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 2,
    teamSizeMaximum: 3,
    certificateAvailability: "Yes",
    description: "Web Wizards challenges teams to design intuitive, accessible, and beautiful digital experiences in a fast-paced 3-round designathon. Judging criteria include usability, creativity, and accessibility compliance.",
    isActive: true,
    posts: [],
  },
  {
    c_by,
    eventName: "GreenTech Sustainability Hackathon",
    organizer: "Thiagarajar College of Engineering",
    mode: "Offline",
    eventDate: new Date("2025-12-20"),
    registrationType: "Team",
    registrationStartDate: new Date("2025-11-15"),
    registrationEndDate: new Date("2025-12-15"),
    totalSeats: 120,
    coverImage: "https://placehold.co/1200x600/2d6a4f/ffffff?text=GreenTech+Hackathon+2025",
    rounds: [
      { roundNumber: "1", roundName: "Problem Identification", roundDescription: "Identify and frame a real-world sustainability problem with supporting data." },
      { roundNumber: "2", roundName: "Solution Sprint", roundDescription: "Build a prototype solution—hardware, software, or a hybrid—in 12 hours." },
      { roundNumber: "3", roundName: "Impact Presentation", roundDescription: "Present projected environmental and social impact to a jury of industry experts and government officials." },
    ],
    schedule: [
      { name: "Opening & Problem Statement Reveal", startTime: "08:00", endTime: "09:00" },
      { name: "Round 1 – Problem Identification", startTime: "09:00", endTime: "11:00" },
      { name: "Solution Sprint Begins", startTime: "11:00", endTime: "11:00" },
      { name: "Overnight Building & Mentoring", startTime: "11:00", endTime: "06:00" },
      { name: "Final Presentations", startTime: "07:00", endTime: "10:00" },
      { name: "Prize Distribution & Closing", startTime: "11:00", endTime: "12:00" },
    ],
    individualFees: 0,
    teamFees: 750,
    lateFees: 200,
    firstPrize: "₹80,000 + Incubation Support",
    secondPrize: "₹40,000",
    thirdPrize: "₹15,000",
    participationPrize: "Certificate + Plantation Kit",
    internshipOpportunity: "Yes",
    placementOpportunity: "Yes",
    industryExposure: "Yes",
    industryPartners: "TNPCB, Grundfos, Envirofit India",
    venueName: "Thiagarajar College of Engineering",
    address: "Thiruparankundram Road",
    city: "Madurai",
    state: "Tamil Nadu",
    pincode: "625015",
    geoLocation: "9.8936,78.0727",
    foodProvide: "Yes",
    vegNonVeg: "Both",
    midnightSnacks: "Yes",
    accommodationProvide: "Yes",
    separatedForBoysGirls: "Yes",
    onlyForOutstationParticipants: "No",
    incharges: [
      { type: "Faculty", name: "Dr. Muthu Krishnan", phoneNumber: "9444401234", mailId: "muthu.k@tce.edu" },
      { type: "Faculty", name: "Dr. Shalini Gopal", phoneNumber: "9500087654", mailId: "shalini.g@tce.edu" },
      { type: "Student", name: "Rahul Balaji", phoneNumber: "9750023456", mailId: "rahul.b@tce.edu" },
    ],
    eligibilityDetails: "Open to all UG/PG students with a passion for sustainability. Interdisciplinary teams strongly encouraged.",
    allowedDepartments: ["CSE", "IT", "Mechanical", "Civil", "EEE", "ECE", "Chemical", "Environmental Engineering"],
    teamOrIndividualEvent: "Team",
    teamSizeMinimum: 3,
    teamSizeMaximum: 5,
    certificateAvailability: "Yes",
    description: "GreenTech is a 24-hour sustainability hackathon focused on solving pressing environmental challenges—clean water, air quality, waste management, and renewable energy. Teams are mentored by government officials and industry leaders throughout the night.",
    isActive: true,
    posts: [],
  },
];

/**
 * Seeds 10 conference documents into the database.
 * Call this after establishing a MongoDB connection.
 */
export async function seedConferences() {
  try {
    const inserted = await Conference.insertMany(conferences, { ordered: false });
    console.log(`✅ Successfully seeded ${inserted.length} conferences.`);
    return inserted;
  } catch (error) {
    console.error("❌ Seeding failed:", error.message);
    throw error;
  }
}

// --- Optional: Run directly with `node seedConferences.js` ---
// Uncomment the block below if you want to run this file standalone.

/*
import "dotenv/config";

(async () => {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log("🔗 Connected to MongoDB");
  await seedConferences();
  await mongoose.disconnect();
  console.log("🔌 Disconnected.");
  process.exit(0);
})();
*/